edits

diff --git a/db_connect/db_connect b/db_connect/db_connect
--- a/db_connect/db_connect
+++ b/db_connect/db_connect
@@ -3,33 +3,34 @@
 CONFIG_FILE="$HOME/.config/db_connect.yaml"
 
 declare -A COMMAND_MAP=(
-  [clickhouse]=clickhouse-client
-  [mysql]=mycli
-  [postgres]=pgcli
-  [mongodb]=mongosh
+	[clickhouse]=clickhouse-client
+	[mysql]=mycli
+	[postgres]=pgcli
+	[mongodb]=mongosh
 )
 
 declare -A PORT_MAP=(
-  [clickhouse]=9000
-  [mysql]=3306
-  [postgres]=5432
-  [mongodb]=27017
+	[clickhouse]=9000
+	[mysql]=3306
+	[postgres]=5432
+	[mongodb]=27017
+)
+
+declare -A INSTAL_MAP=(
+	[yq]="https://github.com/mikefarah/yq?tab=readme-ov-file#install"
+	[fzy]="https://github.com/jhawthorn/fzy?tab=readme-ov-file#installation"
+	[mycli]="https://www.mycli.net/install"
+	[pgcli]="https://www.pgcli.com/install"
+	[clickhouse - client]="https://clickhouse.com/docs/install"
+	[mongosh]="https://www.mongodb.com/docs/mongodb-shell/install/"
 )
 
 function install_error() {
-  declare -A install_map=(
-    [yq]="https://github.com/mikefarah/yq?tab=readme-ov-file#install"
-    [fzy]="https://github.com/jhawthorn/fzy?tab=readme-ov-file#installation"
-    [mycli]="https://www.mycli.net/install"
-    [pgcli]="https://www.pgcli.com/install"
-    [clickhouse - client]="https://clickhouse.com/docs/install"
-    [mongosh]="https://www.mongodb.com/docs/mongodb-shell/install/"
-  )
-  echo "\`$1\` is not installed, install from ${install_map[$1]}"
+	echo "\`$1\` is not installed, install from ${INSTAL_MAP[$1]}"
 }
 
 help() {
-  echo "
+	printf "
 db_connect: keep connection configuration and connect to databases throug network
 commands:
   init           : create config file [$CONFIG_FILE]
@@ -40,13 +41,16 @@ commands:
   completion     : print bash completion
   help           : print this message and exit
 supported databases: ${!PORT_MAP[*]}
-supported tools: ${COMMAND_MAP[*]}
+supported tools    : ${COMMAND_MAP[*]}
+install urls:
 "
+	printf "  %s\n" ${INSTAL_MAP[@]}
+
 }
 
 function bash_completion() {
-  # shellcheck disable=SC2016
-  echo '_complete_db_connect() {
+	# shellcheck disable=SC2016
+	echo '_complete_db_connect() {
   local commands
   local items
   local prev
@@ -80,159 +84,159 @@ complete -F _complete_db_connect db_connect'
 }
 
 function init() {
-  if [ -f "$CONFIG_FILE}" ]; then
-    return
-  fi
-  touch "$CONFIG_FILE"
-  if ! (yq --version &>/dev/null); then
-    install_error "yq"
-  fi
-  if ! (fzy --version &>/dev/null); then
-    install_error "fzy"
-  fi
+	if [ -f "$CONFIG_FILE}" ]; then
+		return
+	fi
+	touch "$CONFIG_FILE"
+	if ! (yq --version &>/dev/null); then
+		install_error "yq"
+	fi
+	if ! (fzy --version &>/dev/null); then
+		install_error "fzy"
+	fi
 }
 
 function add_config() {
-  local name host user pass port db db_type default_port is_srv
-  read -rp "Config name: " name
-  db_type="$(printf "%s\n" "${!COMMAND_MAP[@]}" | fzy --prompt='Select database type: ')"
-  echo "Select database type: $db_type"
-  default_port="${PORT_MAP[$db_type]}"
-  if ! [ "${default_port}" ]; then
-    echo "Database type not supported, should be one of: ${!PORT_MAP[*]}"
-    exit 1
-  fi
-  read -rp "Database host [default: 127.0.0.1]: " host
-  host="${host:-127.0.0.1}"
-  read -rp "Is the host record SRV (default: no) [yes/no]: " is_srv
-  is_srv="${is_srv,,}"
-  if [ "${is_srv}" != 'no' ] && [ "${is_srv}" != "yes" ]; then
-    is_srv='no'
-  fi
-  if [ "${is_srv}" == "no" ]; then
-    read -rp "Database port [default: ${default_port}]: " port
-    port="${port:-$default_port}"
-  else
-    port=""
-  fi
-  read -rp "Database user: " user
-  : "${user:?Database user must be set}"
-  read -rp "Connect database name: " db
-  db="${db:-USE_DEFAULT}"
-  read -rsp "Database password: " pass
-  : "${pass:?Database password must be set}"
-  yq eval -i ".\"$name\".type = \"$db_type\"" "${CONFIG_FILE}"
-  yq eval -i ".\"$name\".host = \"$host\"" "${CONFIG_FILE}"
-  yq eval -i ".\"$name\".port = \"$port\"" "${CONFIG_FILE}"
-  yq eval -i ".\"$name\".user = \"$user\"" "${CONFIG_FILE}"
-  yq eval -i ".\"$name\".pass = \"$pass\"" "${CONFIG_FILE}"
-  yq eval -i ".\"$name\".is_srv = \"$is_srv\"" "${CONFIG_FILE}"
-  yq eval -i ".\"$name\".db = \"$db\"" "${CONFIG_FILE}"
-  echo
+	local name host user pass port db db_type default_port is_srv
+	read -rp "Config name: " name
+	db_type="$(printf "%s\n" "${!COMMAND_MAP[@]}" | fzy --prompt='Select database type: ')"
+	echo "Select database type: $db_type"
+	default_port="${PORT_MAP[$db_type]}"
+	if ! [ "${default_port}" ]; then
+		echo "Database type not supported, should be one of: ${!PORT_MAP[*]}"
+		exit 1
+	fi
+	read -rp "Database host [default: 127.0.0.1]: " host
+	host="${host:-127.0.0.1}"
+	read -rp "Is the host record SRV (default: no) [yes/no]: " is_srv
+	is_srv="${is_srv,,}"
+	if [ "${is_srv}" != 'no' ] && [ "${is_srv}" != "yes" ]; then
+		is_srv='no'
+	fi
+	if [ "${is_srv}" == "no" ]; then
+		read -rp "Database port [default: ${default_port}]: " port
+		port="${port:-$default_port}"
+	else
+		port=""
+	fi
+	read -rp "Database user: " user
+	: "${user:?Database user must be set}"
+	read -rp "Connect database name: " db
+	db="${db:-USE_DEFAULT}"
+	read -rsp "Database password: " pass
+	: "${pass:?Database password must be set}"
+	yq eval -i ".\"$name\".type = \"$db_type\"" "${CONFIG_FILE}"
+	yq eval -i ".\"$name\".host = \"$host\"" "${CONFIG_FILE}"
+	yq eval -i ".\"$name\".port = \"$port\"" "${CONFIG_FILE}"
+	yq eval -i ".\"$name\".user = \"$user\"" "${CONFIG_FILE}"
+	yq eval -i ".\"$name\".pass = \"$pass\"" "${CONFIG_FILE}"
+	yq eval -i ".\"$name\".is_srv = \"$is_srv\"" "${CONFIG_FILE}"
+	yq eval -i ".\"$name\".db = \"$db\"" "${CONFIG_FILE}"
+	echo
 }
 
 function show_config() {
-  if [ "$1" ]; then
-    yq -Poy ".$1" "${CONFIG_FILE}"
-  else
-    yq -Poy "${CONFIG_FILE}"
-  fi
+	if [ "$1" ]; then
+		yq -Poy ".$1" "${CONFIG_FILE}"
+	else
+		yq -Poy "${CONFIG_FILE}"
+	fi
 }
 
 function delete_config() {
-  yq eval -i "del(.$1)" "${CONFIG_FILE}"
+	yq eval -i "del(.$1)" "${CONFIG_FILE}"
 }
 
 function connect() {
-  local name db_type host is_srv port user pass db cmd
-  name="$1"
-  shift
-  host="$(yq ".$name.host" "${CONFIG_FILE}")"
-  port="$(yq ".$name.port" "${CONFIG_FILE}")"
-  user="$(yq ".$name.user" "${CONFIG_FILE}")"
-  pass="$(yq ".$name.pass" "${CONFIG_FILE}")"
-  db_type="$(yq ".$name.type" "${CONFIG_FILE}")"
-  is_srv="$(yq ".$name.is_srv" "${CONFIG_FILE}")"
-  db="$(yq ".$name.db" "${CONFIG_FILE}")"
-  case "${db_type}" in
-  clickhouse)
-    cmd="clickhouse-client"
-    cmd+=" --host $host"
-    cmd+=" --user $user"
-    cmd+=" --port $port"
-    cmd+=" --password $pass"
-    if [ "${db}" != 'USE_DEFAULT' ]; then
-      cmd+=" --database $db"
-    fi
-    ;;
-  mysql)
-    cmd="mycli --ssl"
-    cmd+=" -h $host"
-    cmd+=" -u $user"
-    cmd+=" -P $port"
-    cmd+=" -p $pass"
-    if [ "${db}" != 'USE_DEFAULT' ]; then
-      cmd+=" -D $db"
-    fi
+	local name db_type host is_srv port user pass db cmd
+	name="$1"
+	shift
+	host="$(yq ".$name.host" "${CONFIG_FILE}")"
+	port="$(yq ".$name.port" "${CONFIG_FILE}")"
+	user="$(yq ".$name.user" "${CONFIG_FILE}")"
+	pass="$(yq ".$name.pass" "${CONFIG_FILE}")"
+	db_type="$(yq ".$name.type" "${CONFIG_FILE}")"
+	is_srv="$(yq ".$name.is_srv" "${CONFIG_FILE}")"
+	db="$(yq ".$name.db" "${CONFIG_FILE}")"
+	case "${db_type}" in
+	clickhouse)
+		cmd="clickhouse-client"
+		cmd+=" --host $host"
+		cmd+=" --user $user"
+		cmd+=" --port $port"
+		cmd+=" --password $pass"
+		if [ "${db}" != 'USE_DEFAULT' ]; then
+			cmd+=" --database $db"
+		fi
+		;;
+	mysql)
+		cmd="mycli --ssl"
+		cmd+=" -h $host"
+		cmd+=" -u $user"
+		cmd+=" -P $port"
+		cmd+=" -p $pass"
+		if [ "${db}" != 'USE_DEFAULT' ]; then
+			cmd+=" -D $db"
+		fi
 
-    ;;
-  postgres)
-    cmd="PGPASSWORD=$pass pgcli"
-    cmd+=" -h $host"
-    cmd+=" -u $user"
-    cmd+=" -p $port"
-    if [ "${db}" != 'USE_DEFAULT' ]; then
-      cmd+=" -d $db"
-    fi
-    ;;
-  mongodb)
-    cmd="mongosh"
-    if [ "$is_srv" == 'yes' ]; then
-      cmd+=" mongodb+srv://$user:$pass@$host/"
-    else
-      cmd+=" mongodb://$user:$pass:$host:$port/"
-    fi
-    if [ "${db}" != 'USE_DEFAULT' ]; then
-      cmd+="$db"
-    fi
-    cmd+="?authSource=admin"
-    ;;
-  *) ;;
-  esac
-  eval "$cmd $*"
+		;;
+	postgres)
+		cmd="PGPASSWORD=$pass pgcli"
+		cmd+=" -h $host"
+		cmd+=" -u $user"
+		cmd+=" -p $port"
+		if [ "${db}" != 'USE_DEFAULT' ]; then
+			cmd+=" -d $db"
+		fi
+		;;
+	mongodb)
+		cmd="mongosh"
+		if [ "$is_srv" == 'yes' ]; then
+			cmd+=" mongodb+srv://$user:$pass@$host/"
+		else
+			cmd+=" mongodb://$user:$pass:$host:$port/"
+		fi
+		if [ "${db}" != 'USE_DEFAULT' ]; then
+			cmd+="$db"
+		fi
+		cmd+="?authSource=admin"
+		;;
+	*) ;;
+	esac
+	eval "$cmd $*"
 }
 
 case "${1}" in
 init)
-  init
-  ;;
+	init
+	;;
 completion)
-  bash_completion
-  ;;
+	bash_completion
+	;;
 show)
-  init
-  show_config "$2"
-  ;;
+	init
+	show_config "$2"
+	;;
 add)
-  init
-  add_config "$2" "$3"
-  ;;
+	init
+	add_config "$2" "$3"
+	;;
 delete)
-  init
-  delete_config "$2"
-  ;;
+	init
+	delete_config "$2"
+	;;
 connect)
-  init
-  shift
-  connect "$@"
-  ;;
+	init
+	shift
+	connect "$@"
+	;;
 '-h' | '--help' | 'help')
-  help
-  exit
-  ;;
+	help
+	exit
+	;;
 *)
-  echo -e "\n\033[01;31mError. Command not valid. Valid values are {init|completion|show|add|delete|connect}\033[00m\n"
-  help
-  exit 1
-  ;;
+	echo -e "\n\033[01;31mError. Command not valid. Valid values are {init|completion|show|add|delete|connect}\033[00m\n"
+	help
+	exit 1
+	;;
 esac
